# Generated by Django 4.0 on 2024-03-11 11:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('parse_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField()),
                ('author_url', models.URLField(max_length=500)),
                ('author_name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hub')),
            ],
        ),
    ]
