services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 src/manage.py migrate &&
            python3 src/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  parser:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/manage.py parser
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:16-bullseye"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 2

volumes:
  db_data: